preload = /home/chicken/pictures/backgrounds/crazyfrog1.jpeg
preload = /home/chicken/yeti/2.areas/memes/backgrounds/bugs-full.png
preload = /home/chicken/yeti/2.areas/memes/backgrounds/spongebob-gangster.jpg
wallpaper = DP-2, /home/chicken/yeti/2.areas/memes/backgrounds/spongebob-gangster.jpg
wallpaper = HDMI-A-1, /home/chicken/yeti/2.areas/memes/backgrounds/spongebob-gangster.jpg

